#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$input = new ArgvInput;
$app = require_once __DIR__.'/bootstrap/app.php';
$status = $app->handleCommand($input);

exit($status);
